environment:
    type: "MortarMayhem-Grid"
    name: "MortarMayhem-Grid-v0"
    reset_params:
        start-seed: 0
        num-seeds: 1000
        agent_scale: 0.25
        arena_size: 5
        allowed_commands: 5
        command_count: [10]
        explosion_duration: [2]
        explosion_delay: [5]
        reward_command_failure: 0.0
        reward_command_success: 0.1
        reward_episode_success: 0.0 
gamma: 0.99
lamda: 0.95
updates: 10000
epochs: 8
n_workers: 16
worker_steps: 512
n_mini_batch: 8
value_loss_coefficient: 0.25
hidden_layer_size: 384
transformer:
    num_blocks: 3
    embed_dim: 384
    num_heads: 4
    memory_length: 32
    positional_encoding: ""
    layer_norm: "pre"
learning_rate_schedule:
    initial: 3.0e-4
    final: 1.5e-4
    power: 1.0
    max_decay_steps: 500
beta_schedule:
    initial: 0.001
    final: 0.001
    power: 1.0
    max_decay_steps: 300
clip_range_schedule:
    initial: 0.1
    final: 0.1
    power: 1.0
    max_decay_steps: 300