environment:
    type: "Minigrid"
    name: MiniGrid-MemoryS9-v0
gamma: 0.995
lamda: 0.95
updates: 100
epochs: 5
n_workers: 16
worker_steps: 512
n_mini_batch: 8
value_loss_coefficient: 0.5
hidden_layer_size: 384
max_grad_norm: 0.5
transformer:
    num_blocks: 3
    embed_dim: 384
    num_heads: 4
    memory_length: 64
    positional_encoding: "absolute" # options: "" "absolute" "learned"
learning_rate: 3.5e-4
beta: 0.001
clip_range: 0.1