"env": "Minigrid"
"name": "MiniGrid-MemoryS9-v0"
# "name": "MiniGrid-KeyCorridorS3R1-v0"
"gamma": 0.99
"lamda": 0.95
"updates": 500
"epochs": 4
"n_workers": 16
"worker_steps": 512
"n_mini_batch": 4
"value_loss_coefficient": 0.25
"hidden_layer_size": 512
"episodic_memory":
    "num_layers": 3
    "layer_size": 512
    "num_heads": 4
"learning_rate_schedule":
    "initial": 3.0e-4
    "final": 3.0e-4
    "power": 1.0
    "max_decay_steps": 300
"beta_schedule":
    "initial": 0.001
    "final": 0.001
    "power": 1.0
    "max_decay_steps": 300
"clip_range_schedule":
    "initial": 0.2
    "final": 0.2
    "power": 1.0
    "max_decay_steps": 300